name: .NET Core

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Test
      run: dotnet test
    - name: Publish 
      run: cd TolgPollr.Worker && dotnet publish -r linux-arm --configuration Release /p:PublishSingleFile=true --self-contained
      run: cp -R TolgPollr.Worker/bin/Release/netcoreapp3.0/linux-arm/publish dist
